### ISSUE TITLE
Glob pattern working with 0.5.2 breaks in 1.0.0-beta

### ISSUE THREAD

**Issue by aral** [fatso83/grunt-codekit#14]
```
    codekit:
      all:
        files: [{
          expand: true
          cwd: 'source/'
          src: ['**/*.html']
          dest: 'build'
          ext: '.html'
        }]
```

Will look into it when I get a moment but wanted to document it. Must be due to new glob handling. (We use .html as the extension for kit files for template preview — probably also related to grunt-codekit not expecting that.)

Sample error:

```
Running "codekit:all" (codekit) task
Warning: Unable to write "/Users/aral/ind.ie/projects/site/build/404/index.html/index.html.html" file (Error code: ENOTDIR). Use --force to continue.
```

**Comment by fatso83** [comment]
Finally looking at this. I don't think I ever published a 0.5.2, so I am not sure where that came from? I was unaware of the [options that could be passed in](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically), so that was an eye-opener. Good thing I never got around to releasing the 1.0 ;-)

Just to be 100% sure of what your expected output is:
Given
- the above config
- a project folder with a file located at `source/404/index.html`, relative to this project folder

Then
- you expect to get a file in `build/404/index.html`

Right?

**Comment by fatso83** [comment]
Since there are so many ways of configuring this I believe the simplest fix is to remove the automatic `*.kit` to `*.html` renaming and rather leave that to Grunt, and hope people write sane configurations. Possibly adding it as an optional configuration parameter.

**Comment by fatso83** [comment]
Hopefully I have fixed the issue. Test and report :-) Just reopen if this does not fix your issue. Otherwise, this will be the 1.0 release
